### ISSUE TITLE
Add conda-forge linux channel 

### ISSUE THREAD

**Issue by jan-janssen** [repology/repology-updater#1154] opened 2021-05-29 21:24 UTC
It would be nice to add the conda package manager as it is commonly used for scientific software. My suggestion would be to start with the conda forge linux channel, then other channels can be added later. 

The package index is stored in the JSON format:
https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2 (13.30MB)

**Comment by AMDmi3** [comment] 2021-05-30 11:09
Duplicate of #518. From a quick glance, I see that nothing has improved in the data.

**Closed** 2021-05-30 11:19 UTC
