### ISSUE TITLE
Add FlatHub

### ISSUE THREAD

**Issue by imciner2** [repology/repology-updater#942] opened 2019-11-02 19:25 UTC
It would be nice to add the FlatHub repository (it contains the majority of FlatPak applications). It appears that the package listing can be found through this: https://flathub.org/api/v1/apps.

More details on the API can be found in their implementation of the frontend API calls here: https://github.com/flathub/linux-store-frontend/blob/master/src/app/linux-store-api.service.ts

**Comment by AMDmi3** [comment] 2019-11-02 22:37
Duplicate of #363

**Closed** 2019-11-02 22:37 UTC

**Comment by darkdragon-001** [comment] 2022-11-22 00:58
As the other issue is locked, I am commenting here. The [Apps for GNOME](https://gitlab.gnome.org/World/apps-for-gnome) project is based solely on Flathub applications and parsing it automatically to generate a website. It is doing this via AppStream metainfo files. Maybe this approach would work for repology as well?
