### ISSUE TITLE
Add Chromebrew support

### ISSUE THREAD

**Issue by saltedcoffii** [repology/repology-updater#1236] opened 2022-03-13 01:35 UTC
[Chromebrew](https://github.com/skycocker/chromebrew) is a package manager for ChromeOS and related distros like ChromiumOS, Cloudready, FydeOS, etc. Myself and the other devs would love to see support in repology!
Should upstream support be required, I'm happy to make those modifications.

Thank you so much <3

**Comment by AMDmi3** [comment] 2022-03-13 11:35
I need a json dump of package data, similar to https://formulae.brew.sh/api/formula.json

**Comment by AMDmi3** [comment] 2022-03-17 12:31
Timeout

**Comment by saltedcoffii** [comment] 2022-03-17 18:32
Unfortunately, we don't have any automation (everything we do as far as that goes is done by hand). If I threw together a script that could create a json dump of packages, would you have the means to run it?

**Comment by AMDmi3** [comment] 2022-03-17 18:34
No, we need ready to use data. You can probably use GitHub Actions to run stuff periodically.

**Comment by uberhacker** [comment] 2022-09-06 15:58
@AMDmi3: Just curious how the json file can help.  Chromebrew basically installs everything in `/usr/local`.

**Comment by AMDmi3** [comment] 2022-09-06 18:46
I don't understand the question.

**Comment by uberhacker** [comment] 2022-09-06 18:56
How does having a json file help with compatibility with multiple ChromeOS distros?

**Comment by AMDmi3** [comment] 2022-09-06 19:35
Your questions do not make sense to me. json file is about providing data on packages in chromebrew to repology.

**Comment by uberhacker** [comment] 2022-09-07 21:47
I guess my question is how can repology leverage this data for something useful?

**Comment by AMDmi3** [comment] 2022-09-07 22:04
The overview of what repology does is available on the title page or in the readme.

**Comment by Zopolis4** [comment] 2023-10-18 23:17
Chromebrew now has the required json dump. https://github.com/chromebrew/chromebrew/pull/7376

**Comment by AMDmi3** [comment] 2023-10-19 15:36
@Zopolis4 I don't see an url to the generated file anywhere

**Comment by Zopolis4** [comment] 2023-10-19 21:08
The action runs every Sunday, so it won't have generated one yet.

**Comment by Zopolis4** [comment] 2023-10-25 01:37
The action now runs daily, and has successfully run a few hours ago.

**Comment by AMDmi3** [comment] 2023-10-25 09:49
I still don't have an url

**Comment by AMDmi3** [comment] 2023-10-26 15:24
I guess there's no point in url tied to specific action run as it will never update. Also, repology does not support zip archives. gz/xz/bz2/br/zstd are ok.

**Comment by Zopolis4** [comment] 2023-10-26 23:01
It doesn't seem like there's a way to get github actions to produce a non-zipped artifact, sorry. I'll keeep looking.

**Comment by Zopolis4** [comment] 2024-06-16 02:38
There is now https://raw.githubusercontent.com/chromebrew/chromebrew/master/tools/repology.json, updated weekly.

**Comment by AMDmi3** [comment] 2024-07-04 12:06
- There's no way to tell revisions (as in a2png `0.1.5-2`) from actual versions which use dash as a separator (as in dosbox `0.74-3`)
- No consistent snapshot scheme
- Versions mangled with unrelated stuff (perl, python, glibc versions)
- No way to map package names to recipe names (as in `signal-desktop` in json vs. `signal_desktop.rb`)
- Fake versions (https://raw.githubusercontent.com/chromebrew/chromebrew/master/packages/muparser.rb)

**Comment by Zopolis4** [comment] 2024-07-04 12:33
- I can fix the package to recipe name mapping
- I can also fix the perl, python, etc version tagging
- not sure what you mean about snapshots
- Fake versions I can fix if i'm made aware of them
- Revisions are a tougher one, that might take a few months

**Comment by AMDmi3** [comment] 2024-07-04 14:15
> I can fix the package to recipe name mapping  
> I can also fix the perl, python, etc version tagging

That would be great.

> not sure what you mean about snapshots

- cppdap `1.58.0a-6a3cc9a` (7 nibble hash suffix)
- json-glib `1.8.1-b3774f5` (same, but based on non-existing "next" version)
- crosvm `379dd2d` (7 nibble hash)
- gittools `24eaef0d11e590643e65d188b017b49414d81cc2` (40 nibble hash)
- fskit `dd9a8d`, hyphen `73dd29` (6 nibble hash)
- gpm `1.20.7-e82d` (4 nibble hash suffix)

> Fake versions I can fix if i'm made aware of them

Haven't encountered others beside `muparser` for now. For the record, these can probably be prevented by using `#{version}` in `source_url` in more recipes.


So, hard blockers for Repology are package name mapping (for it prevents Repology from providing links to recipes) and version problems which generate incorrect newest versions. Other version problems just pollute version lists (which is tolerable to some extent given that perl/python/ruby suffixes are fixed as these generate a lot of noise), or report incorrect statuses for Chromebrew (not a problem for Repology, but more of a problem for Chromebrew maintainers).

Incorrect new versions come mostly from revisions and snapshots. If revision handling cannot be fixed in short term (but IMO it should not be too hard to move it into separate field in recipe, still taking into account in package version comparison), we could ignore all versions with dashes, which covers both revisions and snapshots (apart from a few cases which can be ignored manually) and is OK for inclusion. That solution is far from perfect though, as it ignores versions which should not be ignored, prevents new version reporting for some packages and otherwise treats some up to date packages as outdated, but to fix that versioning scheme in Chromebrew should be changed, it's for you to decide if makes sense.

To be compatible with Repology or other tools which order versions (including your own package manager, but since you use commit hashes eagerly I suspect that it only compares for equality), following conditions should be satisfied:
- All snapshots must be based on existing version (e.g. if `1.2.3` is the latest, snapshot would be `1.2.3-XXX` and not `1.2.4-XXX`).
- There must be single uniform and distinguishable scheme for snapshots.
- Versions should not include commit hashes, there are not orderable. You may use dates instead, or, if very must, you may use `git describe --tags` format, which fixes ordering.
For instance, nix uses `1.2.3-unstable-2022-03-15` which satisfies all these conditions.

**Comment by AMDmi3** [comment] 2024-07-04 14:19
Summarizing, I want recipe name mappings and perl/python/ruby/... suffixes fixed to include this, and after that you can gradually unify snapshot scheme and add revision support to make less stuff reported incorrectly.

**Comment by Zopolis4** [comment] 2024-07-04 22:46
Looking at the snapshots, it looks like the majority of commit hashes are 7 long, with a few 4's and one 8-- I'd say itd be a pretty safe bet to just trim any 7 character alphanumerical string, and I can set a standard length for commit hashes after version tags-- would that be the right thing to do?

**Comment by Zopolis4** [comment] 2024-07-04 23:14
> If revision handling cannot be fixed in short term
The problem is that our current build setup means we can't rebuild a package without changing the version, because it overwrites the old build (at least the way we do it now)-- There is a solution, but it has enough blocking issues that it won't be a quick fix.

> but IMO it should not be too hard to move it into separate field in recipe, still taking into account in package version comparison
There is a PR outstanding for this, funnily enough.

**Comment by AMDmi3** [comment] 2024-07-05 15:56
> Looking at the snapshots, it looks like the majority of commit hashes are 7 long, with a few 4's and one 8-- I'd say itd be a pretty safe bet to just trim any 7 character alphanumerical string after a dash, and I can set a standard length for commit hashes after version tags-- would that be the right thing to do?

I prefer not to mangle versions unless there's no other choice. But yes, single scheme of -HHHHHHH is better than 6 different schemes. Not using "next" versions is even more important.

**Closed** 2024-07-08 18:37 UTC
Labels: new source

**Comment by Zopolis4** [comment] 2024-07-26 04:21
Some updates:
- chromebrew/chromebrew#10152 will allow us to no longer use revision tags, after which I can go through and begin to remove them.
- The `-python` and similar tags are stripped out in our data generation, and may also be on the way out entirely in the longer term.
- I've been going through and sorting out snapshots to use release versions when possible, and 7 byte commit hashes when required.
  - I'd prefer not to strip these out in chromebrew's data generation, as in my view this is important information about the version of the package. (as opposed to the `-python3.12` tags, which are there for internal use) 
  - As I understand it, this can be implemented as a global rule in `repology-rules`-- if this is not technically possible, then I can move the logic to chromebrew's data generation.
- There are a number of packages which are marked as unique in chromebrew when they actually just have a different name to the usual one.
  - If a chromebrew package has a different name to upstream, this is a bug in chromebrew (as it interferes with our Anitya integration), and should be fixed there rather than worked around in Repology. I'm working on renaming those packages to match upstream.

**Comment by AMDmi3** [comment] 2024-07-29 16:14
> Some updates:
> 
> * [Download the correct file when there are multiple versions of a package binary. chromebrew/chromebrew#10152](https://github.com/chromebrew/chromebrew/pull/10152) will allow us to no longer use revision tags, after which I can go through and begin to remove them.
> * The `-python` and similar tags are stripped out in our data generation, and may also be on the way out entirely in the longer term.

Superb! Please ping me when revisions are gone, so we could unignore versions containing dashes.

> * I've been going through and sorting out snapshots to use release versions when possible, and 7 byte commit hashes when required.
>   * I'd prefer not to strip these out in chromebrew's data generation, as in my view this is important information about the version of the package. (as opposed to the `-python3.12` tags, which are there for internal use)
>   * As I understand it, this can be implemented as a global rule in `repology-rules`-- if this is not technically possible, then I can move the logic to chromebrew's data generation.

Presence of snapshot addendums is indeed important information and, as long as it's distinguishable, is fine for Repology. However, there's fundamental problem with commit hashes mixed into versions in that these cannot be ordered in a meaningful way, neither against official versions, not among themselves (for instance, according to Repology version comparison algorithm, `1.2.3-a1bcdef` < `1.2.3` < `1.2.3-1abcdef` and there's no way to fix that without breaking ordering of valid versions). That's not a problem for Repology, as snapshot versions compared greater that official would be ignored (there's already global [rule](https://github.com/repology/repology-rules/blob/b271f3f5f802301c20560adb14fa2eacba124be2/899.version-fixes.global.yaml#L25) for all repositories, however it's not completely reliable - see comment), and versions compared lesser than official versions would be considered outdated, and that will not break classification of official versions. However, for repositories using commit hashes false outdated statuses would be reported.

As noted above, there's no way to fix that by changing version comparison algorithm, and though it's technically possible to mark versions lesser than the latest one as ignored instead of outdated, I don't find that practical as it would lead to missed valid outdated status reports. So either you live with a handful of incorrect outdated statuses for snapshot versions, or you could switch to a scheme which supports ordering and/or distinguishes snapshot part in a more clear way so version comparison _could_ made to treat it uniformly. Examples of such schemes would be `1.2.3-unstable-1a2b3c4` (due to additional component we always compare this greater than 1.2.3 and also know for sure it's a snapshot), `1.2.3-unstable-2024-07-29` (same thing, but date based, nix uses this), `1.2.3-g1-1a2b3c4` (`git describe` based, which adds number of commits, both fixing ordering, making a pattern distinguishable and providing some additional info to users). It's up to you to decide on this, Repology can currently support Chromebrew as it is.

> * There are a number of packages which are marked as unique in chromebrew when they actually just have a different name to the usual one.
>   * If a chromebrew package has a different name to upstream, this is a bug in chromebrew (as it interferes with our Anitya integration), and should be fixed there rather than worked around in Repology. I'm working on renaming those packages to match upstream.

I've looked through the list and it looks like there's not too many packages which need name fixing in homebrew. Some rules could be added.

**Comment by AMDmi3** [comment] 2024-09-01 19:31
@Zopolis4 I've got multiple worrying reports involving chromebrew recently, for instance fake openssl 3.3.2 version, fake libevent 2.2 version, fake cairo 1.18.1 version. I've already stated that fake versions or snapshots based on fake (including "future") versions are a show stopper. These should be fixed asap, and chromebrew should have policies against such cases, otherwise we cannot provide Repology support.

**Comment by Zopolis4** [comment] 2024-09-01 22:51
I beleive for libevent we are building off of the `release-2.2.1-alpha` tag, so whether that is a fake version I am not sure.

cairo and openssl are problems though, I will resolve those asap.

**Comment by satmandu** [comment] 2024-09-01 23:23
> @Zopolis4 I've got multiple worrying reports involving chromebrew recently, for instance fake openssl 3.3.2 version, fake libevent 2.2 version, fake cairo 1.18.1 version. I've already stated that fake versions or snapshots based on fake (including "future") versions are a show stopper. These should be fixed asap, and chromebrew should have policies against such cases, otherwise we cannot provide Repology support.

Hi there, I'm the Chromebrew packager that packaged the OpenSSL 3.3.2 version from git, where the version was bumped in the source before an official tag was done. We built from the 3.3 release branch to work on fixing a [bug/regression](https://github.com/openssl/openssl/issues/25249) we encountered that was breaking other packages.

We would love to be able to list on Repology. 

We have been using the internal versions of programs when we build from git to fix issues, and indicating that we are doing so by appending the first seven characters in the relevant git commit.

Do you have a recommendation on how to best handle that? Some packages are abandoned and just don't bother tagging releases for years, despite important fixes appearing in git.

Would you prefer that we use the last official release version with some appended chromebrew version (e.g., like how Ubuntu and Debian do by adding `-debian3.4`)?

**Comment by Zopolis4** [comment] 2024-09-01 23:36
> We have been using the internal versions of programs when we build from git to fix issues, and indicating that we are doing so by appending the first seven characters in the relevant git commit.

That's not what we've being doing in most cases-- most version tags will be the release version thent agged with the git commit, openssl libevent and cairo are exceptions to the rule.

**Comment by satmandu** [comment] 2024-09-02 00:05
> > We have been using the internal versions of programs when we build from git to fix issues, and indicating that we are doing so by appending the first seven characters in the relevant git commit.
> 
> That's not what we've being doing in most cases-- most version tags will be the release version thent agged with the git commit, openssl libevent and cairo are exceptions to the rule.

An appended git commit is added to the release version when we are using a commit to build that is after the released tag.

If that's not the case, we should correct those versions. 😅

**Comment by Zopolis4** [comment] 2024-09-02 00:09
> An appended git commit is added to the release version when we are using a commit to build that is after the released tag.

> If that's not the case, we should correct those versions. 😅

My apologies-- I meant that we append the git commit to the release version (i.e. the one in the tag), rather than the development one in the source.

**Comment by AMDmi3** [comment] 2024-09-03 15:21
> I beleive for libevent we are building off of the release-2.2.1-alpha tag, so whether that is a fake version I am not sure.

By bad, it's not entirely invalid. But not dropping alpha suffix would make it classified as devel and avoid the problem.

> cairo and openssl are problems though

I've got another report for gperf

> I will resolve those asap.

2 days have passed.

**Comment by satmandu** [comment] 2024-09-03 15:39
> > I beleive for libevent we are building off of the release-2.2.1-alpha tag, so whether that is a fake version I am not sure.
> 
> By bad, it's not entirely invalid. But not dropping alpha suffix would make it classified as devel and avoid the problem.
> 
> > cairo and openssl are problems though
> 
> I've got another report for gperf
> 
> > I will resolve those asap.
> 
> 2 days have passed.

Sorry, just to clarify, how would you recommend we tag these versions when they are built from upstream git releases newer than officially tagged upstream releases?

I'm happy to make changes to our build/tag routines, but some guidance on your recommended best practices for these edge cases would really help us avoid these situations in the future. We don't **want** to trip your package-has-a-nonsensical-version unit tests. 😅

**Comment by AMDmi3** [comment] 2024-09-03 18:37
> Sorry, just to clarify, how would you recommend we tag these versions when they are built from upstream git releases newer than officially tagged upstream releases?

Short answer: last official version + optionally distinguishable snapshot suffix.

The suffix format must be such that it's unlikely to be encountered in upstream versions, so we could reliably match it with a pattern and treat correspondingly, and it should not mess up with the version ordering. For instance, `X.Y.Z-unstable-YYYY-MM-DD` which nix uses is ok, `X.Y.Z.YYYYMMDD`, `X.Y.Z.HHHHHHH` are not (dates may be part of upstream versions, hashes cannot be ordered against official version meaningfully, also 8-char hashes alias with dates). `X.Y.Z.gHHHHHHH` is okish though. Last official version without any suffixes is fine too. If you provide snapshot information separately from a version (e.g. in separate repology.json field), that would be the best.

Why absolutely not "next" version, even explicitly marked as snapshot? Because it's not known whether it will be `X.Y.(Z+1)`, `X.(Y+1).0`, `(X+1).0.0`, `X.Y.Z.1`, completely another scheme, or won't ever be, and if you're unlucky you either produce fake new version which upsets other maintainers, or your version is classified as outdated while it isn't, or your version won't be outdated by newer upstream release while it should. Even if upstream mentions "in development" version, that's not reliable, and since not everybody does that, this approach is not general.

See also [docs](https://repology.org/docs/requirements).

> I'm happy to make changes to our build/tag routines, but some guidance on your recommended best practices for these edge cases would really help us avoid these situations in the future. We don't **want** to trip your package-has-a-nonsensical-version unit tests. 😅

These are unfortunately not unit tests, these are living package maintainers from other distributions complaining that fake new versions are reported to them.

**Comment by satmandu** [comment] 2024-09-03 20:10
> These are unfortunately not unit tests, these are living package maintainers from other distributions complaining that fake new versions are reported to them.

Sorry, that was me being glib. Yes we would like to avoid these situations. Thanks for the guidance.

@uberhacker FYI...
