### ISSUE TITLE
include gentoo tree while testing overlay package list

### ISSUE THREAD

**Issue by blshkv** [repology/repology-updater#213] opened 2017-04-19 06:25 UTC
hello, I'm a developer of Pentoo Linux which is an overlay of Gentoo.
First of all, thank you for the great job. This project is amazing!

As you know, Gentoo overlays are just extensions of the main Gentoo tree.
Often, we bump a new version ahead of Gentoo. However, we don't always remove it after Gentoo has included the same version or even bumped a newer one.

Currently, repology would report an outdated package in the overlay even if there is a newer version in the main tree. This is useful for maintainers (so that we can clean up it eventually) but confusing for users.

Could you create a marker (different color, blue?) to indicate that there is a newer version in the main tree?

Thank you

**Comment by AMDmi3** [comment] 2017-04-19 12:10
I don't see a problem for Pentoo users as Repology just reports the actual package state and if a package is outdated in Pentoo, it *is* outdated and I don't see a reason to not show it as such. The newer version may be in Gentoo or any other distro, I don't see why these cases should be differentiated.

It's usually more of a problem for maintainers, as there are multiple cases where outdatedness is normal and does not imply any actions to be taken by maintainer, such as:

- lagacy versions of some packages (e.g. older library or compiler for projects which are not compatible with newer versions)
  - outdatedness does not count
  - however it's possible to match packages within a single major branch (e.g. for version `0.8`, version `0.9` is counted, but not `1.0`)
- "stable" repos such as Debian Stable which do not allow package updates
  - outdatedness counts, but no action required
- secondary repos such as DPorts, which is merely a mirror of FreeBSD ports with some lag
  - outdatedness counts, but no action required

Taking these into account is pretty complex task as it is, but actually there's even more complexity:

- complex package relations, in addition to legacy versions mentioned above
  - subpackages, e.g. `foo-client` and `foo-server` merged into single `foo` metapackage
    - outdatedness counts
  - devel versions, e.g. prerelease/unstable branches
    - these should either not be treated as newest versions or be split into separate metapackages. Repology already handles these pretty well.
  - parallel package hierarchies, e.g. `libfoo`/`lib32-libfoo`/`mingw32-libfoo`
    - should probably share newest versions, but it doesn't seem like a good solution to stick all these into a single metapackage. this won't allow to see repos in which mingw32 libs are missing, for instance
- complex repository relations, in addition to stable and mirror repos mentioned above:
  - partial clones, which may have additional packages (such as Manjaro, Parabola are to Arch)
  - related repos such as Arch and AUR, Gentoo and overlays, probably CentOS and EPEL
- joined repositories may need to be handled in some way, e.g. arch + aur, debian stable + backports, probably gentoo + overlay(s).

As you can see, the problem is really large and complex and I don't see a generic solution to it yet. I definitely plan to improve it in future, but for now I'm afraid we'll have to stick with plain straightforward approach where we just directly compare versions between all repos treating them as (almost) unrelated entities. As already mentioned, I don't think this affects Pentoo much. I'll keep the issue open though.

PS. I've added Pentoo support on random - I just did a quick research on Gentoo overlays and added first repo which looked fresh and alive. Could you maybe suggest additional overlays to add, which are alive and widely used?

**Comment by blshkv** [comment] 2017-04-19 13:09
you see, my point is that overlays are not only "related", they are actually extensions of the mail Gentoo tree.  So if we don't have glibc (for example), it doesn't mean we don't have it all. Pentoo will include the latest stable from Gentoo. The same with any other package. We might have an outdated package but it doesn't mean that it will be installed. Portage (our packet manager) will pull the latest from either of repositories.

So Pentoo is something like Gentoo+overlay. It's not a standalone tree.

But, again, I'm happy with the way how it is now, it helps us to clean up the outdated packages. 

I just suggest to make an additional step for forward, if there is a better version exist in Gentoo, mark the current outdated Pentoo package in blue.

**Comment by AMDmi3** [comment] 2017-04-19 13:18
Again, I don't see a difference. Outdated is outdated, newest is newest. Even if you merge gentoo+pentoo, outdated package will stay outdated.

**Comment by blshkv** [comment] 2017-04-19 13:25
Often, there are several packages of different versions in Gentoo tree alone, but you will display the highest available. There is no difference if these different versions are in different locations (overlay) from my point of view, but it is your call of cause.

btw, there full list of "official" overlays is below:
http://www.gentoo.org/proj/en/overlays/repositories.xml

there is also a basic stats about activity http://gpo.zugaina.org/Newest

https://github.com/Sabayon/sabayon-distro
https://github.com/Sabayon/for-gentoo

**Comment by blshkv** [comment] 2017-04-19 13:26
these two bugs ( https://github.com/repology/repology/issues/200 ) are related somehow ;-)

**Comment by AMDmi3** [comment] 2017-04-19 16:11
Yes, there's a patch which enables all ebuilds. I don't think anything is holding it, just needs some testing.

I have an idea of a rough solution for this problem, btw:
- introduce an extra package state, let's call it _legacy_
- if a given repo has newest version of a package, other versions are _legacy_ instead of outdated

Similar logic is already used in "outdated for maintainer" metapackage list - e.g. if there's newest package, outdated ones are ignored.

Now, we can extend this logic onto multiple repositories. We already arrange repositories into families (gentoo and overlays are a single family), and this logic can work within a family, so an outdated package in an overlay would be considered _legacy_ instead of _outdated_ - this is essentially the "blue color" you've asked for.

However just the families concept is not enough for this bacause repositories are usually not equivalent, as while outdated package in Pentoo/Debian Stable/DPorts is just legacy, outdated package in Gentoo/Debian Unstable/FreeBSD **is really** outdated. So we need parent/child relationships between repos. With majority of related repos, this should actually work.

**Comment by AMDmi3** [comment] 2017-04-19 16:16
> btw, the full list of "official" overlays is below:
> http://www.gentoo.org/proj/en/overlays/repositories.xml
> 
> there is also a basic stats about activity http://gpo.zugaina.org/Newest

I've seen these, but it still doesn't give an idea which of overlays are alive, fresh and widely used.

> the most complex one would be the overlay of Sabayon (just a wild guess)
> https://github.com/Sabayon/sabayon-distro

This is already supported

> https://github.com/Sabayon/for-gentoo

This could be added

**Comment by blshkv** [comment] 2017-04-19 16:20
yeah, the new _legacy_ status sounds perfect. Thank you!

**Comment by AMDmi3** [comment] 2017-04-20 13:14
Ok, this is doable, but it has somewhat low priority compared to other features I plan to fix/implement.

**Comment by Chemrat** [comment] 2017-08-02 16:38
> I've seen these, but it still doesn't give an idea which of overlays are alive, fresh and widely used.

All overlays on the official list are required to have some minimal level of maintenance, e.g. pass automatic QA and handle overlay-related bugs. Dead overlays are usually removed (see https://github.com/gentoo/api-gentoo-org/commits/master/files/overlays)

**Comment by AMDmi3** [comment] 2017-08-02 18:44
Hm, OK. But adding them in bulk is too much for repology to handle (mainly from the user interface standpoint) for now, so I'll add them by request.

**Comment by AMDmi3** [comment] 2017-11-17 16:39
Just a note, there's a complete list of packages in all Gentoo overlays http://git.exherbo.org/layman_repositories.tar.bz2

**Closed** 2020-11-04 18:25 UTC
Labels: core
