### ISSUE TITLE
Check upstream first to tag a new release

### ISSUE THREAD

**Issue by TimB87** [repology/repology-updater#1111] opened 2021-01-17 12:51 UTC
Hi,

sorry, I am still on a low time frame, else I would keep contributing to falsely advertised versions that seem to be the speciality of a few distros/maintainers.
I came around this project: https://release-monitoring.org/project/7927/

This would check upstream sources to announce new versions and does not rely on maintainers to push to whatever they came up with. Do you see a possibility to implement some way of this functionality into repology?

Best regards
Tim

**Comment by AMDmi3** [comment] 2021-01-17 15:23
Duplicate of #938

**Closed by AMDmi3** 2021-01-17 15:23 UTC
Labels: duplicate
