### ISSUE TITLE
[feature suggestion] Monitor Rust crates repository for Rust apps

### ISSUE THREAD

**Issue by yurivict** [repology/repology-updater#1096] opened 2020-11-23 19:15 UTC
If Repology could pull Rust crates that are in the category "Command line utilities" on https://crates.io/crates. it would be helping (1) to update Rust ports to the latest version, and (2) to discover unported Rust apps.

For example, the search for "ods2sql" could find not only the FreeBSD port, but also the corresponding Rust crate page https://crates.io/crates/ods2sql

**Comment by AMDmi3** [comment] 2020-11-23 20:08
- Repology already pulls info on _all_ crates, see https://repology.org/project/ods2sql/related for this example (they are omitted from the projects list not to pollute it with tons of uninteresting entries, likewise for all other upstream module collections like rubygems, cpan and pypi).
- There's no way we can rely on crates.io category here, as it contains a lot of libraries as well.
- Otherwise this is a duplicate of #637. There's no solution for it right now, so rules for individual projects are welcome. Added one for ods2sql.

**Comment by yurivict** [comment] 2020-11-23 20:10
> There's no way we can rely on crates.io category here, as it contains a lot of libraries as well.

But when the category is "Command line utilities" it has to contain a program, no?

**Comment by AMDmi3** [comment] 2020-11-23 20:48
I'm not the one to ask this. The fact is that it does contain libraries, so it can't be used for this task.

**Comment by yurivict** [comment] 2020-11-23 20:56
When the category is "Command line utilities", it has to contain an executable "command".

This is true for known commands https://crates.io/crates/bat, https://crates.io/crates/ods2sql, https://crates.io/crates/fd-find.
Rust libraries don't have the "Command line utilities" category.

So if Repology would filter out only entries from crates.io that contain the category "Command line utilities" and let them appear in searches this would be an improvement. Commands are potential targets for porting. This is true for 3 crates listed above, and should be true for all other crates that have the "Command line utilities" category.

**Comment by AMDmi3** [comment] 2020-11-23 21:39
> and should be true for all other crates that have the "Command line utilities" category.

Like I've already said, it's not.

**Closed by AMDmi3** 2020-11-23 21:39 UTC

**Comment by yurivict** [comment] 2020-11-23 21:43
> Like I've already said, it's not.

Why not?

**Comment by AMDmi3** [comment] 2020-11-23 22:51
I don't understand the question. It's the fact that "Command line utilities" category contains libraries - you can check it yourself, first two entries are libraries. You should ask their developers "why" it is so.
