### ISSUE TITLE
Track project upstream sources for new versions not in any repo yet

### ISSUE THREAD

**Issue by Atemu** [repology/repology-updater#1062] opened 2020-06-23 09:00 UTC
Repology tracks a ton of repos but there might still be newer versions of projects that haven't been packaged anywhere yet.

It'd be nice if Repology could track the upstream sources of projects for new (release) versions and expose them to the user.  

Such a feature would be especially useful for maintainers who'd like to keep their packages as up-to-date as possible and automated tools like @r-ryantm which make use of Repology data to help them in that mission.

**Comment by AMDmi3** [comment] 2020-06-23 23:28
Duplicate of #1, #938

**Closed by AMDmi3** 2020-06-23 23:28 UTC
